dist: trusty
language: c
matrix:
  include:
  - env: CLANG=clang-4.0
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
        - python3-pip
        - python3-setuptools
  - env: CLANG=clang-5.0
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
        - clang-tools-5.0
        - python3-pip
        - python3-setuptools
install:
- python3 -m pip install --user pydiatra pyflakes
- python3 -m pip install --user pygments restructuredtext-lint
script:
- make -C tests CC=$CLANG SANCOV=sancov-${CLANG#clang-}
- python3 -m pydiatra .
- python3 -m pyflakes .
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
