dist: trusty
sudo: false
language: c
matrix:
  include:
  - env: CLANG=clang-4.0
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
  - env: CLANG=clang-5.0
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
script:
- make -C tests CC=$CLANG SANCOV=sancov-${CLANG#clang-}

# vim:ts=2 sts=2 sw=2 et
