name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - clang: clang-12
          python: python-3.9
          os: ubuntu-22.04
        - clang: clang-13
          python: python-3.10
          os: ubuntu-22.04
        - clang: clang-14
          python: python-3.11
          os: ubuntu-22.04
        - clang: clang-15
          python: python-3.12
          os: ubuntu-22.04
        - clang: clang-16
          python: python-3.13
          os: ubuntu-24.04
        - clang: clang-17
          python: python-3.13
          os: ubuntu-24.04
        - clang: clang-18
          python: python-3.13
          os: ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: extract version numbers
      run: |
        echo "clang-ver=${clang#clang-}" >> $GITHUB_ENV
        echo "python-ver=${python#python-}" >> $GITHUB_ENV
      env:
        clang: ${{matrix.clang}}
        python: ${{matrix.python}}
    - name: set up Python ${{env.python-ver}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{env.python-ver}}
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install clang ${{env.clang-ver}}
      run: |
        sudo apt-get install -y clang-${{env.clang-ver}} clang-tools-${{env.clang-ver}}
    - name: run tests
      run:
        make -C tests CC=clang-${{env.clang-ver}} SANCOV=sancov-${{env.clang-ver}}
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        python -m pyflakes .
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra -v .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
