name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - clang: clang-4.0
          python: python-3.6
          os: ubuntu-18.04
        - clang: clang-5.0
          python: python-3.6
          os: ubuntu-18.04
        - clang: clang-6.0
          python: python-3.6
          os: ubuntu-18.04
        - clang: clang-7
          python: python-3.6
          os: ubuntu-20.04
        - clang: clang-8
          python: python-3.7
          os: ubuntu-20.04
        - clang: clang-9
          python: python-3.8
          os: ubuntu-20.04
        - clang: clang-10
          python: python-3.9
          os: ubuntu-20.04
        - clang: clang-11
          python: python-3.10
          os: ubuntu-20.04
        - clang: clang-12
          python: python-3.11
          os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: extract version numbers
      run: |
        echo "clang-ver=${clang#clang-}" >> $GITHUB_ENV
        echo "python-ver=${python#python-}" >> $GITHUB_ENV
      env:
        clang: ${{matrix.clang}}
        python: ${{matrix.python}}
    - name: set up Python ${{env.python-ver}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{env.python-ver}}
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install clang ${{env.clang-ver}}
      run: |
        sudo apt-get install -y clang-${{env.clang-ver}} clang-tools-${{env.clang-ver}}
    - name: run tests
      run:
        make -C tests CC=clang-${{env.clang-ver}} SANCOV=sancov-${{env.clang-ver}}
    - name: run pyflakes
      run: |
        pyflakes=pyflakes
        if [[ ${{env.python-ver}} = 3.3 ]]; then pyflakes+='<2'; fi
        python -m pip install $pyflakes
        python -m pyflakes .
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra -v .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
